/**
 * PDF Service for Invoice Generation
 * Generates professional Algerian invoices in PDF format
 */

interface InvoiceData {
  invoice_number: string;
  invoice_date: string;
  due_date: string;
  amount: number;
  tax_rate: number;
  tax_amount: number;
  total_amount: number;
  client?: {
    first_name: string;
    last_name: string;
    email?: string;
    phone?: string;
    address?: string;
  };
  case?: {
    title: string;
  };
  items?: Array<{
    description: string;
    quantity: number;
    unit_price: number;
    total: number;
  }>;
  notes?: string;
}

interface LawyerInfo {
  name: string;
  barreau: string;
  address: string;
  phone: string;
  email: string;
  nif?: string;
  rc?: string;
}

/**
 * Generate PDF invoice (browser-based)
 * Uses HTML to PDF conversion for simplicity
 */
export const generateInvoicePDF = async (
  invoice: InvoiceData,
  lawyerInfo: LawyerInfo
): Promise<Blob> => {
  // Create HTML template for invoice
  const html = createInvoiceHTML(invoice, lawyerInfo);
  
  // Convert HTML to PDF using browser print
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    throw new Error('Could not open print window');
  }
  
  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.focus();
  
  // Trigger print dialog
  setTimeout(() => {
    printWindow.print();
  }, 250);
  
  // Return empty blob (actual PDF generated by browser)
  return new Blob([], { type: 'application/pdf' });
};

/**
 * Create HTML template for invoice
 */
const createInvoiceHTML = (invoice: InvoiceData, lawyerInfo: LawyerInfo): string => {
  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('fr-DZ', {
      style: 'currency',
      currency: 'DZD',
      minimumFractionDigits: 2
    }).format(amount);
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('fr-FR', {
      day: '2-digit',
      month: '2-digit',
      year: 'numeric'
    });
  };

  return `
    <!DOCTYPE html>
    <html lang="fr">
    <head>
      <meta charset="UTF-8">
      <title>Facture ${invoice.invoice_number}</title>
      <style>
        @page { size: A4; margin: 2cm; }
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { 
          font-family: 'Segoe UI', Arial, sans-serif; 
          font-size: 11pt; 
          line-height: 1.6;
          color: #333;
        }
        .container { max-width: 800px; margin: 0 auto; padding: 20px; }
        .header { 
          display: flex; 
          justify-content: space-between; 
          margin-bottom: 40px;
          border-bottom: 3px solid #D4AF37;
          padding-bottom: 20px;
        }
        .logo { font-size: 24pt; font-weight: bold; color: #D4AF37; }
        .invoice-title { 
          font-size: 28pt; 
          font-weight: bold; 
          color: #1e293b;
          text-align: right;
        }
        .info-section { margin-bottom: 30px; }
        .info-grid { 
          display: grid; 
          grid-template-columns: 1fr 1fr; 
          gap: 30px; 
        }
        .info-box { 
          background: #f8fafc; 
          padding: 15px; 
          border-radius: 8px;
          border-left: 4px solid #D4AF37;
        }
        .info-box h3 { 
          font-size: 12pt; 
          color: #64748b; 
          margin-bottom: 10px;
          text-transform: uppercase;
          letter-spacing: 0.5px;
        }
        .info-box p { margin: 5px 0; }
        .invoice-details { 
          background: #1e293b; 
          color: white; 
          padding: 15px; 
          border-radius: 8px;
          margin-bottom: 30px;
        }
        .invoice-details table { width: 100%; }
        .invoice-details td { padding: 5px 10px; }
        .invoice-details td:first-child { font-weight: bold; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        thead { background: #1e293b; color: white; }
        th { 
          padding: 12px; 
          text-align: left; 
          font-weight: 600;
          text-transform: uppercase;
          font-size: 9pt;
          letter-spacing: 0.5px;
        }
        td { padding: 12px; border-bottom: 1px solid #e2e8f0; }
        tbody tr:hover { background: #f8fafc; }
        .text-right { text-align: right; }
        .totals { 
          margin-top: 30px; 
          float: right; 
          width: 300px;
        }
        .totals table { margin: 0; }
        .totals td { 
          padding: 8px 12px; 
          border: none;
        }
        .totals tr:last-child { 
          background: #D4AF37; 
          color: white; 
          font-weight: bold;
          font-size: 14pt;
        }
        .footer { 
          margin-top: 60px; 
          padding-top: 20px; 
          border-top: 2px solid #e2e8f0;
          text-align: center;
          color: #64748b;
          font-size: 9pt;
        }
        .notes { 
          background: #fef3c7; 
          padding: 15px; 
          border-radius: 8px;
          margin: 20px 0;
          border-left: 4px solid #f59e0b;
        }
        @media print {
          body { print-color-adjust: exact; -webkit-print-color-adjust: exact; }
          .no-print { display: none; }
        }
      </style>
    </head>
    <body>
      <div class="container">
        <!-- Header -->
        <div class="header">
          <div>
            <div class="logo">JuristDZ</div>
            <p style="color: #64748b; margin-top: 5px;">Cabinet d'Avocat</p>
          </div>
          <div class="invoice-title">FACTURE</div>
        </div>

        <!-- Info Grid -->
        <div class="info-grid">
          <div class="info-box">
            <h3>Cabinet</h3>
            <p><strong>${lawyerInfo.name}</strong></p>
            <p>${lawyerInfo.barreau}</p>
            <p>${lawyerInfo.address}</p>
            <p>Tél: ${lawyerInfo.phone}</p>
            <p>Email: ${lawyerInfo.email}</p>
            ${lawyerInfo.nif ? `<p>NIF: ${lawyerInfo.nif}</p>` : ''}
            ${lawyerInfo.rc ? `<p>RC: ${lawyerInfo.rc}</p>` : ''}
          </div>

          <div class="info-box">
            <h3>Client</h3>
            ${invoice.client ? `
              <p><strong>${invoice.client.first_name} ${invoice.client.last_name}</strong></p>
              ${invoice.client.address ? `<p>${invoice.client.address}</p>` : ''}
              ${invoice.client.phone ? `<p>Tél: ${invoice.client.phone}</p>` : ''}
              ${invoice.client.email ? `<p>Email: ${invoice.client.email}</p>` : ''}
            ` : '<p>-</p>'}
          </div>
        </div>

        <!-- Invoice Details -->
        <div class="invoice-details">
          <table>
            <tr>
              <td>N° Facture:</td>
              <td><strong>${invoice.invoice_number}</strong></td>
              <td>Date:</td>
              <td><strong>${formatDate(invoice.invoice_date)}</strong></td>
            </tr>
            <tr>
              <td>Dossier:</td>
              <td>${invoice.case?.title || '-'}</td>
              <td>Échéance:</td>
              <td><strong>${formatDate(invoice.due_date)}</strong></td>
            </tr>
          </table>
        </div>

        <!-- Items Table -->
        <table>
          <thead>
            <tr>
              <th>Description</th>
              <th class="text-right">Quantité</th>
              <th class="text-right">Prix Unitaire</th>
              <th class="text-right">Total</th>
            </tr>
          </thead>
          <tbody>
            ${invoice.items?.map(item => `
              <tr>
                <td>${item.description}</td>
                <td class="text-right">${item.quantity}</td>
                <td class="text-right">${formatCurrency(item.unit_price)}</td>
                <td class="text-right"><strong>${formatCurrency(item.total)}</strong></td>
              </tr>
            `).join('') || `
              <tr>
                <td>Honoraires d'avocat</td>
                <td class="text-right">1</td>
                <td class="text-right">${formatCurrency(invoice.amount)}</td>
                <td class="text-right"><strong>${formatCurrency(invoice.amount)}</strong></td>
              </tr>
            `}
          </tbody>
        </table>

        <!-- Totals -->
        <div class="totals">
          <table>
            <tr>
              <td>Montant HT:</td>
              <td class="text-right"><strong>${formatCurrency(invoice.amount)}</strong></td>
            </tr>
            <tr>
              <td>TVA (${invoice.tax_rate}%):</td>
              <td class="text-right"><strong>${formatCurrency(invoice.tax_amount)}</strong></td>
            </tr>
            <tr>
              <td>TOTAL TTC:</td>
              <td class="text-right"><strong>${formatCurrency(invoice.total_amount)}</strong></td>
            </tr>
          </table>
        </div>

        <div style="clear: both;"></div>

        <!-- Notes -->
        ${invoice.notes ? `
          <div class="notes">
            <strong>Notes:</strong><br>
            ${invoice.notes}
          </div>
        ` : ''}

        <!-- Footer -->
        <div class="footer">
          <p>Merci de votre confiance</p>
          <p style="margin-top: 10px;">
            Paiement par virement bancaire ou espèces<br>
            En cas de retard de paiement, des pénalités de 10% seront appliquées
          </p>
        </div>
      </div>
    </body>
    </html>
  `;
};

/**
 * Download invoice as PDF
 */
export const downloadInvoicePDF = async (
  invoice: InvoiceData,
  lawyerInfo: LawyerInfo
): Promise<void> => {
  await generateInvoicePDF(invoice, lawyerInfo);
};

export default {
  generateInvoicePDF,
  downloadInvoicePDF
};
